examples/bash/echo.sh, examples/python/echo.py, internal/provider/file.go
And return nil or err to the message processor. Allowing for not ack'ing messages if file plugin had failures.
Verifed running with multiple plugin urls would create a provider for each url, which allows for multiplexing plugins.
=> [SM-6465][SM-6390] Adjust file plugin to listen for OK or ERR from stdout

internal/migrator/types.go, internal/model/model.go
This was truncating the type on update, resulting in invalid sql
=> SM-8650: fix issue  with update sql generation

internal/migrator/diff.go
Previous logic flow for diffModels function:
Loop 1: loop through all the columns of the table already stored in the customer's DB and compare it to the schema columns that we grab from nats. 
Loop 2: loop through all the columns of the schema we grabbed from nats and compare it to the columns already in the customer's DB table.
We were running into an issue where when iterating through that first full loop, we create a ModelChange variable and set the change action to NoAction. In that second loop, if we found a column that needed to be added, we'd add the column's info to the change variable, but the overall change action would still be "NoAction", meaning we wouldn't make any adjustments to the DB table. 
Logic flow now:
Initialize change variable before looping and set action to …
=> [SM-9252] Fix bug where we aren't adding new columns that we find in the latest schema

internal/migrator/migrator.go, internal/provider/snowflake.go
Functionally, gosnowflake seems to do this conversion under the hood (ie: if you give the snowflake driver a connection string, it'll convert it to a DSN Config and open a driver using that config), but I wanted to roll-out this fix as a sanity check. 
Here's the connection string produced by doing this conversion vs what we currently input:
Conversion- "loginCredentials@<organization_name>.snowflakecomputing.com:443?account=<organization_name>&client_session_keep_alive=true&database=<database>&ocspFailOpen=true&schema=<schema>&validateDefaultParameters=true&warehouse=<warehouse>"
Original- "loginCredentials@<organization_name>/<database>/<schema>?warehouse=<warehouse>&client_session_keep_alive=true"
=> [SM-9338] Adding experimental fix for snowflake connector timing out

cmd/root.go, cmd/server.go, internal/processor.go, internal/provider/postgresql.go, internal/provider/snowflake.go, internal/provider/sqlserver.go
Previously, in server.go, we would iterate through the connection string URLs provided in our args and create a NATS message processor for each connection string URL provided. This was causing NATS messages to be round-robinned between the providers, with a single provider acknowledging the NATS message before any other providers could access the message. 
In this change, we now create a single NATS message processor, with all of the providers pulling from this message processor and processing the message before we acknowledge the NATS message. 
Console logging showcasing that the same message is processed by both a postgresql provider and a sqlserver provider:
=> [RBR-350] creating 1 NATS message processor for all of the providers rather than a separate NATS message processor for each provider

internal/util/util.go, internal/util/util_test.go
When using the `v2.1.1-rc` release, I noticed that our database password was not fully masked. This ended up being caused by our password containing a `@` character and the masking regex was using lazy matching. After swapping to greedy matching, passwords with `@` characters will now be fully masked.
The only future risk with this change would be if a value beyond the password contains an `@` character. However, the effect of that would be that even more of the connection string would become masked which is not harmful.
=> @ characters in connection string passwords no longer break masking

cmd/root.go, cmd/server.go, go.mod, go.sum, internal/processor.go, internal/provider/file.go, internal/provider/init.go, internal/provider/nats.go, internal/provider/postgresql.go, internal/provider/snowflake.go, internal/provider/sqlserver.go, server.conf, stream.conf
Technical Details:
This spins up a local NATS server that our database providers now read from. Functionally, there are now 2 NATS messaging processors. The first one is still connected to our main Shopmonkey NATS, but looking at the dbchange stream. This messaging processor contains one provider (a NATS provider), which then republishes those dbchange messages to the local NATS server. The second NATS messaging processor is connected to our local NATS server, and will contain our database providers. 
The processors also share a schema model cache now. Previously, message processors would make a request if there was not a schema stored. Because of the shared schema model cache, the first message processor will make the schema request and the schema update will be shared by the other …
=> [RBR-216] Adding leaf-node support for EDS

internal/provider/file.go
We've encountered a case where the file provider is getting stuck extending messages again.
It appears that the `readStout` function is saving the result of `p.scanner.Text()` to a variable and then switching on `p.scanner.Text()` again. While this shouldn't normally be a problem on its own, based on the image below the `OK` that our Python sends back was received and logged directly by eds-server.  The only place I see where that could occur is the default switch case. And if correct, that would mean that the second call to `p.scanner.Text()` somehow resulted in a different value that was not `OK` or `ERR` because the default case logs the `line` variable, which contains the result of the first call to `p.scanner.Text()`
I am currently unsure how or where the scanner would be moved to …
=> Fixing an issue that may be causing the file provider to become stuck

internal/provider/file.go
Use a contains to allow for tying messageIds to pipe traffic
=> [hotfix] add contains to logs on file provider pipes

examples/python/nats-provider.py, go.mod, internal/datatypes/changeevent.go, internal/processor.go, internal/provider/nats.go
This will add the Nats-Msg-Id to the re-published message:
=> [RBR-1052] add header to republished nats message and update example to show header

internal/util/util.go
See: https://github.com/shopmonkeyus/eds-server/blob/main/internal/model/model.go#L205
=> [RBR-1328] use timestamptz instead of timestamp_tz to match how we write sql type for snowflake

cmd/fork.go, cmd/import.go, cmd/root.go, cmd/server.go, internal/consumer/consumer.go, internal/metrics.go, internal/notification/notification.go, internal/util/file.go
Replaces `--log-file-sink` on `fork` with a logs dir inside the datadir and a smarter log sink that can `Rotate` whereby it switches writing to a new file and returns the completed previous log file. This can then be requested by the server via the http control plane. The server then gets control of the file, it compresses it, requests an upload url from Shopmonkey, uploads the file, and, on success, deletes it from disk. This assures that we dont run out of disk space for long-running servers.
Logs are automatically uploaded hourly. The server can be told to upload logs by publishing a notification with the action `sendlogs`.
`fork` merely exposes an ability to rotate the log and get back the last file, its up to `server` to manage rotations/uploads.
- the heartbeat payload was giant and …
=> [VCARB-61] Upload log file

cmd/fork.go, cmd/root.go, cmd/server.go
- log files use unix time instead of isodate
- add route replacer for the api change
- fail the server if it cant create a log sink
=> V3.1.2 Windows fixes

cmd/fork.go, cmd/root.go, cmd/server.go, go.mod, go.sum, internal/drivers/snowflake/snowflake.go, internal/notification/notification.go
- returns a non-zero exit code when fork errors
- uploads **ALL** logs:
- every hour
- on request
- at shutdown
- on (fork) panic
=> Fix log upload to work in both happy and panic paths

internal/consumer/consumer.go, internal/metrics.go
Adds a new top level metric called Processing Duration that will track from first new payload received all the way to when it is flushed to destionation.
=> Metric: add processing duration histogram metric which tracks from first payload to flush to driver destination

cmd/enroll.go, cmd/root.go, internal/util/zip.go
https://www.loom.com/share/9dc0a348851d4a1f8305b6c9c227e673
Testing:
- run this backend branch locally https://github.com/shopmonkeyus/backend/pull/7018
- Create a server in postman pointed at your local env
- Grab the `code`
- example: go run . enroll --code {code} --api-url https://api-de35bc.shopmonkey.cloud
=> [VCARB-94] - Added new enroll cmd

cmd/enroll.go, cmd/fork.go, cmd/import.go, cmd/server.go, docker-compose.yaml, go.mod, go.sum, internal/consumer/consumer.go, internal/dbchange.go, internal/drivers/eventhub/eventhub.go, internal/drivers/file/file.go, internal/drivers/kafka/kafka.go, internal/drivers/mysql/mysql.go, internal/drivers/mysql/sql.go, internal/drivers/s3/s3.go, internal/importer.go, internal/importer/importer.go, internal/registry/api.go, internal/util/api.go, internal/util/api_test.go, internal/util/batcher.go, internal/util/errors.go, internal/util/http.go
Refactor import to maximize reuse across multiple drivers.
Added import support for Kafka, EventHub and AWS.
Fixed batching issue with EventHub adding duplicates into batches.
Use the API Key to set the default API URL.
Fixed enroll API path for non localhost.
Add `imported` flag on DBChange during import so upstream drivers can use this to know when the event is from an import or replay
=> [VCARB-108] [VCARB-71] [VCARB-57] [VCARB-56] Import support for Kafka, EventHub and S3 and refactored for reuse

cmd/fork.go, cmd/import.go, cmd/root.go, go.mod, go.sum, internal/consumer/consumer.go, internal/dbchange.go, internal/driver.go, internal/drivers/s3/s3.go, internal/importer.go, internal/importer/importer.go, internal/schema.go, internal/util/batcher.go, internal/util/schema.go, internal/util/schema_test.go, internal/util/testdata/base/message.json, internal/util/testdata/config.json, internal/util/testdata/labor_message.json, internal/util/testdata/models/labor.json
Initial implementation of using a JSON schema to validate both import and event processing.
Set using `--schema-validator`
Example:
```
go run . import --url "s3://localhost:4566/test" --schema-validator ./datadir/schema --api-key $TOKEN  --verbose --data-dir ./datadir
```
Create a folder schema with the following:
```json
{
"labor": {
"schema": "labor_message.json",
"path": "{{.table}}/received/{{.table}}_{{.mvccTimestamp}}_{{.id}}.json"
},
"message": {
"schema": "base/message.json",
"path": "{{.table}}/received/{{.table}}_{{.mvccTimestamp}}_{{.id}}.json"
}
}
```
And copy the test files from `./internal/util/testdata` into this folder
=> [VCARB-78] add support for schema validation for server/import using JSON schema

internal/drivers/s3/s3.go, internal/drivers/sqlserver/sqlserver.go, internal/util/mask.go, internal/util/mask_test.go
- improve driver by allowing config to be set in url
- fix occasional panic on shutdown
url example with config:
```
s3://bucket/folder?region=us-west-2&access-key-id=AKIAIOSFODNN7EXAMPLE&secret-access-key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```
- fix build issue with Flush signature change
- improve masking to only mask query string values instead of the keys
=> S3 improvements, masking improvements, fix SQL Server impl

internal/util/schema.go, internal/util/schema_test.go, internal/util/testdata/models/labor.json
Looks like the json schema library we support works with a number of json schema formats out of the box. This PR adds a test case to validate their usage and also improves the error message when a schema validation fails.
=> [VCARB-136] add test case for JSON schema validation with format support and improve schema validation issue

cmd/import.go, cmd/server.go, internal/driver.go, internal/drivers/eventhub/eventhub.go, internal/drivers/file/file.go, internal/drivers/kafka/kafka.go, internal/drivers/mysql/mysql.go, internal/drivers/postgresql/postgresql.go, internal/drivers/s3/s3.go, internal/drivers/snowflake/snowflake.go, internal/drivers/sqlserver/sqlserver.go, internal/importer.go, internal/importer/importer.go, internal/notification/notification.go
Adds end-to-end configure url and import logic.  Also refactors the Driver interface to be able to test the connection url.
NOTE: in a subsequent PR going to separate out the configure / import messages but this is a good first iteration for end-to-end testing in the app.
Requires https://github.com/shopmonkeyus/backend/pull/7213 for import on configure to work
=> [VCARB-140] add configuration import

cmd/import.go, cmd/server.go, internal/consumer/consumer.go, internal/notification/notification.go
This adds a separate import action which will run async.  This must only be called after configure is called.
Configure will now only validate the url.
=> Add separate import action

cmd/root.go
Instead of showing full path to binary on *nix systems when you're running the binary for the CWD, just show ./eds instead.
Trim the extra space when no arguments passed in
=> Small Quality of Life issue

cmd/server.go, internal/consumer/consumer.go
before it was sending the sig-int and immediately starting the new server. The old server would then shutdown and end the active session
=> [VCARB-203] Wait for old session to close before starting a new one

README.md, cmd/driver_eventhub.go, cmd/driver_file.go, cmd/driver_kafka.go, cmd/driver_mysql.go, cmd/driver_postgres.go, cmd/driver_s3.go, cmd/driver_snowflake.go, cmd/driver_sqlserver.go, cmd/root.go, cmd/server.go
Adds support for building a binary that only has one driver. By default, will build all.
Updated README with instructions.
=> [VCARB-215] Support Building Smaller Binary

cmd/server.go
Prevents you from running with "" in your `token` field in the config file
=> [VCARB-175] verify token before starting up

cmd/server.go
@robindiddams made a change just before release to pass in --api-url to enroll when overridden but the codepath will set a default if not explicitly passed in which will force stable url by default instead of using the enrollment code prefix.
This change will only pass it down if explicitly set in commandline
=> [VCARB-260] Regression: only override the api-url in enroll if explicitly overriden in command line

go.sum, internal/drivers/s3/s3.go, internal/drivers/s3/s3_test.go
When using schema validation, make sure we include the S3 path prefix in the calculated output filename.
@athomas-byrider this will fix your issue.
=> [VCARB-277] S3: when using schema validation path, make sure to include the S3 path prefix

cmd/import.go, internal/importer.go, internal/importer/importer.go
Adds ability to replay data from a time offset
```
go run . import --api-key $TOKEN --url $URL -v --timeOffset '2024-05-01T00:00:00Z' --no-delete
```
2 new flags to import:
- `timeOffset` optional date time in RFC3339 format
- `no-delete` optional flag to tell importer not to drop and recreate tables
=> [VCARB-306] add ability to replay data from a specific time offset

internal/drivers/s3/s3.go, internal/drivers/s3/s3_test.go, internal/e2e/driver_s3.go
This may break workflows for companies making use of our S3 Driver. Before merging and releasing the new version, any companies using the S3 driver should be informed of these changes!
=> [LOTUS-5324] potentially breaking change: Adds timestamp to s3 driver record file names

.github/workflows/e2e.yaml, cmd/fork.go, cmd/server.go, internal/driver.go, internal/drivers/snowflake/snowflake.go, internal/drivers/snowflake/sql.go, internal/drivers/snowflake/sql_test.go, internal/e2e/driver_snowflake.go, internal/notification/notification.go
The current implementation of the Snowflake driver can generate invalid data when changefeed events arrive out of order.
This PR does two things. It adds an option for a new update strategy that uses the entire `after` field in the dbchange event and only updates if the incoming record's timestamp is later than the `updatedDate` of the existing record. It also switches to use upsert (merge in snowflake) to avoid the problem of an insert event arriving out of order.
For the curious, `viper` handles reading the config file for the EDS server located in /data/config.toml. Additional work will need to be done to the front end to allow the update strategy to be configured in the SM EDS flow. For now it must be set in the config file.
Added a unit test for the new merge statement (snowflake's …
=> [LOTUS-5613] EDS Snowflake Driver Update Whole Record If Newer

.gitignore
the gitignore file doesn't exclude the .vscode artifacts directory or the eds-debug binary (which you need to attach to the fork process). This adds several dozen keystrokes to each commit which costs dearly in engineering time.
=> [LOTUS-5632] Update gitignore
