internal/processor.go

Note: The message that isn't processed successfully will still need to be handled somehow by the provider (whether manually or through EDS), so there will most likely need to be follow-up work for this.
Tested these 3 cases:
1.) 2 Providers created- SQL Server, and PostGres provider. I had the PostGres provider trigger an error when trying to process a message, and the overall program successfully exited.
2.) 2 Providers created- SQL Server, and PostGres provider. I had both of the providers trigger an error when trying to process the same message, and the overall program continued to run, but logged the error.
3.) 1 Provider created- PostGres provider. The postgres provider triggered an error and continued to run, but logged the error.

[RBR-488] closing EDS when multiple providers go out of sync for processing the same message

---

internal/processor.go
internal/provider/file.go

Handle case when EOF could be returned before OK or ERR and add more logging.

[hotfix]Handle eof

---

internal/processor.go

removing the scenario where we close EDS in the case of it already seeing a message that it has previously acked

[RBR-1356] ignore a nats message if we've already acked it before

---

.github/workflows/docker.yml
Dockerfile
docker-compose.yaml

Upgrade dependencies

---

cmd/import.go
cmd/root.go
internal/drivers/file/file.go

Adds a file driver which is useful for testing and development.

[VCARB-104] add file driver for testing

---

internal/util/api.go

helps peeps not issue a new token

Support Legacy tokens

---

cmd/import.go
cmd/root.go
cmd/server.go
go.mod
go.sum

- **cleanup request paths**
- **better error**

Error handling + api url cleanup

---

cmd/fork.go
cmd/import.go
cmd/server.go
internal/consumer/consumer.go

This is mostly for debugging, since passing it can screw up your consumer. helpful though for testing etc

Allow filtering down company ids in the server command

---

cmd/fork.go

Broken the cli tool with a little mistake

---

cmd/enroll.go
cmd/fork.go
cmd/server.go
internal/notification/notification.go

- **server will wait until it is configured with a url**
- **better logs**

[VCARB-135] Allow remote url configuration

---

cmd/enroll.go

A few small enrollment tweaks from using it ...
- Provide a better error message when the enrollment code is invalid or previously used
- Provide a more accurate command line instruction for starting the server

Enrollment tweaks

---

cmd/server.go
internal/notification/notification.go
internal/util/http.go

sends intermediary statuses so we can update the UI

[VCARB-181] Communicate status better

---

cmd/fork.go
cmd/server.go
internal/consumer/consumer.go
internal/consumer/credentials.go
internal/notification/notification.go

- restart now cycles the forked server process
- this effectively will always renew so i remove renew

[VCARB-201] Restart should start a new session

---

internal/driver.go

- URL decoding before sending back URL. The postgres password was getting turned into %21
- Default port always getting set used
- The optional int tool will cast an string to an int if it can.

[VCARB-174] added a couple bug fixes

---

internal/notification/notification.go

The frontend change is with the dynamic drivers PR: https://github.com/shopmonkeyus/frontend/pull/5615
backend: https://github.com/shopmonkeyus/backend/pull/7451

[VCARB-205] - Made configure action request reply

---

internal/processor.go

this will keep creating a new consumer even if we want it to load a bunch of messages over time

removes appending start time to consumer

---

.gitignore
.goreleaser.yaml
go.sum
internal/driver.go

Adds hook for running macos sign and notarize step for goreleaser
https://linear.app/shopmonkey/issue/VCARB-86/code-sign-the-build-on-release

[VCARB-86] Add MacOS sign and notarize step for release prep

---

cmd/server.go
internal/notification/notification.go

[VCARB-251] Better Logging around pauses

---

.goreleaser.yaml

Remove ld flags from golang

---

cmd/fork.go
cmd/import.go
cmd/root.go
internal/consumer/consumer.go

- **allow starting EDS without any previous import session data**
- **cleanup unused state**

[VCARB-270] Allow starting eds without an import timestamp

---

internal/consumer/consumer.go
internal/importer/importer.go
internal/util/schema.go

Need to differentiate between an ERROR and WARN for valid schema validation failures.

[VCARB-276] schema validation should log debug instead of error

---

go.sum
internal/drivers/mysql/sql.go
internal/drivers/postgresql/sql.go
internal/drivers/sqlserver/sql.go
internal/drivers/sqlserver/sql_test.go

This was the offending sql:
```
UPDATE "phone_number" SET number='1',"crdb_region"='gcp-us-central1',NULL,NULL,NULL,NULL WHERE id='abc'
```

[VCARB-282] incorrect update sql server for update with NULL

---

.github/workflows/e2e.yaml
cmd/fork.go
cmd/server.go
go.sum
internal/consumer/consumer.go
internal/consumer/consumer_test.go
internal/drivers/kafka/kafka.go
internal/drivers/sqlserver/sql.go
internal/e2e/e2e.go
internal/util/json.go
internal/util/json_test.go

Handles a case where we have a modelVersion mismatch (bug in SM processing in copy tool) caused a database SQL insert error.

[VCARB-307] Exit with special error code if we detect a schema mismatch

---

internal/registry/api.go

EDS cautiously updates the versions of all models in the API schema on start, but it also uses the presence of the version key to decide whether to add a new table to the target database or not. This change will only update the versions of existing keys so the table creation will still function properly.

[LOTUS-6422] Dropping Target DB Results in EDS SQL errors
